// Zero - Complete export file
// All Zero client functionality and Epic-008 model integration
//
// Auto-generated: 2025-08-08 04:43:39 UTC
//
// ⚠️  Do not edit this file manually - it will be regenerated
// To regenerate: rails generate zero:active_models

// Zero client initialization and management
export {
  initZero,
  getZero,
  getZeroAsync,
  getZeroState,
  closeZero,
  reinitializeZero,
} from './zero-client';

// Zero schema types
export { schema, type ZeroClient } from './generated-schema';

// Epic-008 models are now managed in /lib/models/ instead of legacy .generated files
// Use the Epic-008 models directly for reliable, reactive data access:
//
// import { ClientsFrontConversation, ReactiveClientsFrontConversation } from '$lib/models/clients-front-conversations';
// import { ContactMethod, ReactiveContactMethod } from '$lib/models/contact-methods';
// import { Device, ReactiveDevice } from '$lib/models/devices';
//
// Legacy .generated.ts files have been removed as part of Epic-008 cleanup.

// Re-export Zero library types for convenience
export type { Zero } from '@rocicorp/zero';
