version: 0.9.0
project:
  name: bos
  description: ''
  version: 0.9.0
editor:
  default: code
templates:
  directory: templates
defaults:
  assignee: null
tasks:
  directory: tickets
  auto_id: true
  id_format: TSK-{counter:04d}
git:
  auto_commit: false
  commit_prefix: '[ai-trackdown]'
plugins: {}
paths:
  tickets_dir: tickets
  epics_dir: tickets/epics
  issues_dir: tickets/issues
  tasks_dir: tickets/tasks
