// 🤖 AUTO-GENERATED LOGGABLE CONFIGURATION
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated by Rails generator
// Run: rails generate zero:active_models

export const LOGGABLE_MODELS = {
  clients: { modelName: 'Client', includesLoggable: true },
  devices: { modelName: 'Device', includesLoggable: true },
  jobs: { modelName: 'Job', includesLoggable: true },
  people: { modelName: 'Person', includesLoggable: true },
  people_group_memberships: { modelName: 'PeopleGroupMembership', includesLoggable: true },
  people_groups: { modelName: 'PeopleGroup', includesLoggable: true },
  scheduled_date_times: { modelName: 'ScheduledDateTime', includesLoggable: true },
  tasks: { modelName: 'Task', includesLoggable: true },
  users: { modelName: 'User', includesLoggable: true },
} as const;

export type LoggableModelName = keyof typeof LOGGABLE_MODELS;

export function isLoggableModel(tableName: string): tableName is LoggableModelName {
  return tableName in LOGGABLE_MODELS;
}

export function getLoggableModelInfo(tableName: LoggableModelName) {
  return LOGGABLE_MODELS[tableName];
}
