/**
 * ActivityLogData - TypeScript interface for activity_logs table
 * * Relationships (loaded via includes()):
 * - user: belongs_to User
 * - client: belongs_to Client
 * - job: belongs_to Job
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { UserData } from './user-data';
import type { ClientData } from './client-data';
import type { JobData } from './job-data';

/**
 * Complete ActivityLog record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ActivityLogData extends BaseRecord {
  id: string;
  action?: string;
  loggable_type: string;
  metadata?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
  user_id?: string;
  client_id?: string;
  job_id?: string;
  loggable_id?: string;
  user?: UserData; // belongs_to
  client?: ClientData; // belongs_to
  job?: JobData; // belongs_to
}

/**
 * Create ActivityLog data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateActivityLogData = Omit<
  ActivityLogData,
  'id',
  'created_at',
  'updated_at',
  'user',
  'client',
  'job'
>;

/**
 * Update ActivityLog data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateActivityLogData = Partial<
  Omit<ActivityLogData, 'id', 'created_at', 'updated_at', 'user', 'client', 'job'>
>;
