/**
 * ClientFrontConversationData - TypeScript interface for clients_front_conversations table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ClientFrontConversation record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ClientFrontConversationData extends BaseRecord {
  id: string;
  client_id: string;
  front_conversation_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create ClientFrontConversation data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateClientFrontConversationData = Omit<
  ClientFrontConversationData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update ClientFrontConversation data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateClientFrontConversationData = Partial<
  Omit<ClientFrontConversationData, 'id', 'created_at', 'updated_at'>
>;
