/**
 * ClientData - TypeScript interface for clients table
 * * Relationships (loaded via includes()):
 * - activityLogs: has_many ActivityLog
 * - people: has_many Person
 * - jobs: has_many Job
 * - devices: has_many Device
 * - peopleGroups: has_many PeopleGroup
 * - clientsFrontConversations: has_many ClientsFrontConversation
 * - frontConversations: has_many FrontConversation, through: clients_front_conversations
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { ActivityLogData } from './activity-log-data';
import type { PersonData } from './person-data';
import type { JobData } from './job-data';
import type { DeviceData } from './device-data';
import type { PeopleGroupData } from './people-group-data';
import type { ClientsFrontConversationData } from './clients-front-conversation-data';
import type { FrontConversationData } from './front-conversation-data';

/**
 * Complete Client record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ClientData extends BaseRecord {
  id: string;
  name?: string;
  created_at: string | number;
  updated_at: string | number;
  name_normalized?: string;
  client_type: 'residential' | 'business';
  activityLogs?: ActivityLogData[]; // has_many
  people?: PersonData[]; // has_many
  jobs?: JobData[]; // has_many
  devices?: DeviceData[]; // has_many
  peopleGroups?: PeopleGroupData[]; // has_many
  clientsFrontConversations?: ClientsFrontConversationData[]; // has_many
  frontConversations?: FrontConversationData[]; // has_many
}

/**
 * Create Client data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateClientData = Omit<
  ClientData,
  'id',
  'created_at',
  'updated_at',
  'activityLogs',
  'people',
  'jobs',
  'devices',
  'peopleGroups',
  'clientsFrontConversations',
  'frontConversations'
>;

/**
 * Update Client data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateClientData = Partial<
  Omit<
    ClientData,
    'id',
    'created_at',
    'updated_at',
    'activityLogs',
    'people',
    'jobs',
    'devices',
    'peopleGroups',
    'clientsFrontConversations',
    'frontConversations'
  >
>;
