/**
 * FrontConversationTicketData - TypeScript interface for front_conversation_tickets table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontConversationTicket record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontConversationTicketData extends BaseRecord {
  id: string;
  front_conversation_id: string;
  front_ticket_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontConversationTicket data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontConversationTicketData = Omit<
  FrontConversationTicketData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update FrontConversationTicket data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontConversationTicketData = Partial<
  Omit<FrontConversationTicketData, 'id', 'created_at', 'updated_at'>
>;
