/**
 * FrontAttachmentData - TypeScript interface for front_attachments table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontAttachment record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontAttachmentData extends BaseRecord {
  id: string;
  front_message_id: string;
  filename?: string;
  content_type?: string;
  url?: string;
  size?: number;
  metadata?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontAttachment data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontAttachmentData = Omit<FrontAttachmentData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontAttachment data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontAttachmentData = Partial<
  Omit<FrontAttachmentData, 'id', 'created_at', 'updated_at'>
>;
