/**
 * FrontConversationData - TypeScript interface for front_conversations table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontConversation record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontConversationData extends BaseRecord {
  id: string;
  front_id: string;
  subject?: string;
  status?: string;
  status_category?: string;
  status_id?: string;
  is_private?: boolean;
  created_at_timestamp?: number;
  waiting_since_timestamp?: number;
  custom_fields?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  links?: Record<string, unknown>;
  scheduled_reminders?: Record<string, unknown>;
  api_links?: Record<string, unknown>;
  assignee_id?: string;
  recipient_contact_id?: string;
  created_at: string | number;
  updated_at: string | number;
  last_message_front_id?: string;
  recipient_handle?: string;
  recipient_role?: string;
}

/**
 * Create FrontConversation data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontConversationData = Omit<
  FrontConversationData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update FrontConversation data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontConversationData = Partial<
  Omit<FrontConversationData, 'id', 'created_at', 'updated_at'>
>;
