/**
 * FrontTicketData - TypeScript interface for front_tickets table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontTicket record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontTicketData extends BaseRecord {
  id: string;
  front_id?: string;
  ticket_id?: string;
  subject?: string;
  status?: string;
  status_category?: string;
  status_id?: string;
  created_at_timestamp?: number;
  updated_at_timestamp?: number;
  custom_fields?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  api_links?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontTicket data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontTicketData = Omit<FrontTicketData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontTicket data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontTicketData = Partial<
  Omit<FrontTicketData, 'id', 'created_at', 'updated_at'>
>;
