/**
 * FrontMessageData - TypeScript interface for front_messages table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontMessage record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontMessageData extends BaseRecord {
  id: string;
  front_id: string;
  front_conversation_id: string;
  message_uid?: string;
  message_type?: string;
  is_inbound?: boolean;
  is_draft?: boolean;
  subject?: string;
  blurb?: string;
  body_html?: string;
  body_plain?: string;
  error_type?: string;
  draft_mode?: string;
  metadata?: Record<string, unknown>;
  api_links?: Record<string, unknown>;
  created_at_timestamp?: number;
  author_id?: string;
  created_at: string | number;
  updated_at: string | number;
  author_type?: string;
  author_handle?: string;
  author_name?: string;
}

/**
 * Create FrontMessage data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontMessageData = Omit<FrontMessageData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontMessage data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontMessageData = Partial<
  Omit<FrontMessageData, 'id', 'created_at', 'updated_at'>
>;
