/**
 * FrontContactData - TypeScript interface for front_contacts table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontContact record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontContactData extends BaseRecord {
  id: string;
  front_id?: string;
  name?: string;
  handle?: string;
  role?: string;
  handles?: Record<string, unknown>;
  api_links?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontContact data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontContactData = Omit<FrontContactData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontContact data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontContactData = Partial<
  Omit<FrontContactData, 'id', 'created_at', 'updated_at'>
>;
