/**
 * FrontTagData - TypeScript interface for front_tags table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontTag record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontTagData extends BaseRecord {
  id: string;
  front_id: string;
  name: string;
  highlight?: string;
  description?: string;
  is_private?: boolean;
  is_visible_in_conversation_lists?: boolean;
  created_at_timestamp?: number;
  updated_at_timestamp?: number;
  parent_tag_id?: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontTag data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontTagData = Omit<FrontTagData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontTag data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontTagData = Partial<Omit<FrontTagData, 'id', 'created_at', 'updated_at'>>;
