/**
 * FrontSyncLogData - TypeScript interface for front_sync_logs table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontSyncLog record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontSyncLogData extends BaseRecord {
  id: string;
  resource_type: string;
  sync_type: string;
  status: string;
  started_at: string | number;
  completed_at?: string | number;
  duration_seconds?: number;
  records_synced?: number;
  records_created?: number;
  records_updated?: number;
  records_failed?: number;
  error_messages?: string;
  metadata?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontSyncLog data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontSyncLogData = Omit<FrontSyncLogData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontSyncLog data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontSyncLogData = Partial<
  Omit<FrontSyncLogData, 'id', 'created_at', 'updated_at'>
>;
