/**
 * FrontTeammateData - TypeScript interface for front_teammates table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontTeammate record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontTeammateData extends BaseRecord {
  id: string;
  front_id: string;
  email?: string;
  username?: string;
  first_name?: string;
  last_name?: string;
  is_admin?: boolean;
  is_available?: boolean;
  is_blocked?: boolean;
  teammate_type?: string;
  custom_fields?: Record<string, unknown>;
  api_links?: Record<string, unknown>;
  created_at_timestamp?: number;
  updated_at_timestamp?: number;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontTeammate data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontTeammateData = Omit<FrontTeammateData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontTeammate data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontTeammateData = Partial<
  Omit<FrontTeammateData, 'id', 'created_at', 'updated_at'>
>;
