/**
 * FrontConversationTagData - TypeScript interface for front_conversation_tags table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontConversationTag record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontConversationTagData extends BaseRecord {
  id: string;
  front_conversation_id: string;
  front_tag_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontConversationTag data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontConversationTagData = Omit<
  FrontConversationTagData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update FrontConversationTag data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontConversationTagData = Partial<
  Omit<FrontConversationTagData, 'id', 'created_at', 'updated_at'>
>;
