/**
 * FrontMessageRecipientData - TypeScript interface for front_message_recipients table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontMessageRecipient record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontMessageRecipientData extends BaseRecord {
  id: string;
  front_message_id: string;
  front_contact_id?: string;
  role: string;
  handle: string;
  name?: string;
  api_links?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontMessageRecipient data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontMessageRecipientData = Omit<
  FrontMessageRecipientData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update FrontMessageRecipient data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontMessageRecipientData = Partial<
  Omit<FrontMessageRecipientData, 'id', 'created_at', 'updated_at'>
>;
