/**
 * FrontInboxData - TypeScript interface for front_inboxes table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontInbox record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontInboxData extends BaseRecord {
  id: string;
  front_id: string;
  name: string;
  inbox_type?: string;
  handle?: string;
  settings?: Record<string, unknown>;
  api_links?: Record<string, unknown>;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontInbox data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontInboxData = Omit<FrontInboxData, 'id', 'created_at', 'updated_at'>;

/**
 * Update FrontInbox data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontInboxData = Partial<Omit<FrontInboxData, 'id', 'created_at', 'updated_at'>>;
