/**
 * FrontConversationInboxData - TypeScript interface for front_conversation_inboxes table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete FrontConversationInbox record interface
 * Matches the database schema exactly with optional relationships
 */
export interface FrontConversationInboxData extends BaseRecord {
  id: string;
  front_conversation_id: string;
  front_inbox_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create FrontConversationInbox data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateFrontConversationInboxData = Omit<
  FrontConversationInboxData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update FrontConversationInbox data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateFrontConversationInboxData = Partial<
  Omit<FrontConversationInboxData, 'id', 'created_at', 'updated_at'>
>;
