/**
 * JobPersonData - TypeScript interface for job_people table
 * * Relationships (loaded via includes()):
 * - job: belongs_to Job
 * - person: belongs_to Person
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { JobData } from './job-data';
import type { PersonData } from './person-data';

/**
 * Complete JobPerson record interface
 * Matches the database schema exactly with optional relationships
 */
export interface JobPersonData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  job_id?: string;
  person_id?: string;
  job?: JobData; // belongs_to
  person?: PersonData; // belongs_to
}

/**
 * Create JobPerson data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateJobPersonData = Omit<
  JobPersonData,
  'id',
  'created_at',
  'updated_at',
  'job',
  'person'
>;

/**
 * Update JobPerson data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateJobPersonData = Partial<
  Omit<JobPersonData, 'id', 'created_at', 'updated_at', 'job', 'person'>
>;
