/**
 * JobAssignmentData - TypeScript interface for job_assignments table
 * * Relationships (loaded via includes()):
 * - job: belongs_to Job
 * - user: belongs_to User
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { JobData } from './job-data';
import type { UserData } from './user-data';

/**
 * Complete JobAssignment record interface
 * Matches the database schema exactly with optional relationships
 */
export interface JobAssignmentData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  job_id?: string;
  user_id?: string;
  job?: JobData; // belongs_to
  user?: UserData; // belongs_to
}

/**
 * Create JobAssignment data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateJobAssignmentData = Omit<
  JobAssignmentData,
  'id',
  'created_at',
  'updated_at',
  'job',
  'user'
>;

/**
 * Update JobAssignment data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateJobAssignmentData = Partial<
  Omit<JobAssignmentData, 'id', 'created_at', 'updated_at', 'job', 'user'>
>;
