/**
 * ParsedEmailData - TypeScript interface for parsed_emails table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ParsedEmail record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ParsedEmailData extends BaseRecord {
  id: string;
  parseable_type: string;
  parseable_id: string;
  plain_message?: string;
  plain_signature?: string;
  html_message?: string;
  html_signature?: string;
  parse_options?: string;
  parsed_at?: string | number;
  parser_version?: string;
  parse_errors?: string;
  content_hash?: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create ParsedEmail data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateParsedEmailData = Omit<ParsedEmailData, 'id', 'created_at', 'updated_at'>;

/**
 * Update ParsedEmail data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateParsedEmailData = Partial<
  Omit<ParsedEmailData, 'id', 'created_at', 'updated_at'>
>;
