/**
 * PeopleGroupMembershipData - TypeScript interface for people_group_memberships table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete PeopleGroupMembership record interface
 * Matches the database schema exactly with optional relationships
 */
export interface PeopleGroupMembershipData extends BaseRecord {
  id: string;
  person_id: string;
  people_group_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create PeopleGroupMembership data interface
 * Excludes auto-generated fields and relationships
 */
export type CreatePeopleGroupMembershipData = Omit<
  PeopleGroupMembershipData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update PeopleGroupMembership data interface
 * All fields optional except id, excludes relationships
 */
export type UpdatePeopleGroupMembershipData = Partial<
  Omit<PeopleGroupMembershipData, 'id', 'created_at', 'updated_at'>
>;
