/**
 * PeopleGroupData - TypeScript interface for people_groups table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete PeopleGroup record interface
 * Matches the database schema exactly with optional relationships
 */
export interface PeopleGroupData extends BaseRecord {
  id: string;
  name: string;
  is_department: boolean;
  client_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create PeopleGroup data interface
 * Excludes auto-generated fields and relationships
 */
export type CreatePeopleGroupData = Omit<PeopleGroupData, 'id', 'created_at', 'updated_at'>;

/**
 * Update PeopleGroup data interface
 * All fields optional except id, excludes relationships
 */
export type UpdatePeopleGroupData = Partial<
  Omit<PeopleGroupData, 'id', 'created_at', 'updated_at'>
>;
