/**
 * PeopleFrontConversationData - TypeScript interface for people_front_conversations table
 *
 * Generated from Rails schema: 2025-08-04 22:23:45 UTC
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete PeopleFrontConversation record interface
 * Matches the database schema exactly with optional relationships
 */
export interface PeopleFrontConversationData extends BaseRecord {
  id: string;
  person_id: string;
  front_conversation_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create PeopleFrontConversation data interface
 * Excludes auto-generated fields and relationships
 */
export type CreatePeopleFrontConversationData = Omit<
  PeopleFrontConversationData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update PeopleFrontConversation data interface
 * All fields optional except id, excludes relationships
 */
export type UpdatePeopleFrontConversationData = Partial<
  Omit<PeopleFrontConversationData, 'id', 'created_at', 'updated_at'>
>;
