/**
 * PersonFrontConversationData - TypeScript interface for people_front_conversations table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete PersonFrontConversation record interface
 * Matches the database schema exactly with optional relationships
 */
export interface PersonFrontConversationData extends BaseRecord {
  id: string;
  person_id: string;
  front_conversation_id: string;
  created_at: string | number;
  updated_at: string | number;
}

/**
 * Create PersonFrontConversation data interface
 * Excludes auto-generated fields and relationships
 */
export type CreatePersonFrontConversationData = Omit<
  PersonFrontConversationData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update PersonFrontConversation data interface
 * All fields optional except id, excludes relationships
 */
export type UpdatePersonFrontConversationData = Partial<
  Omit<PersonFrontConversationData, 'id', 'created_at', 'updated_at'>
>;
