/**
 * ScheduledDateTimeData - TypeScript interface for scheduled_date_times table
 * * Relationships (loaded via includes()):
 * - activityLogs: has_many ActivityLog
 * - scheduledDateTimeUsers: has_many ScheduledDateTimeUser
 * - users: has_many User, through: scheduled_date_time_users
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';
import type { ActivityLogData } from './activity-log-data';
import type { ScheduledDateTimeUserData } from './scheduled-date-time-user-data';
import type { UserData } from './user-data';

/**
 * Complete ScheduledDateTime record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ScheduledDateTimeData extends BaseRecord {
  id: string;
  schedulable_type: string;
  scheduled_type: string;
  notes?: string;
  created_at: string | number;
  updated_at: string | number;
  schedulable_id?: string;
  scheduled_at?: string | number;
  scheduled_time_set: boolean;
  activityLogs?: ActivityLogData[]; // has_many
  scheduledDateTimeUsers?: ScheduledDateTimeUserData[]; // has_many
  users?: UserData[]; // has_many
}

/**
 * Create ScheduledDateTime data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateScheduledDateTimeData = Omit<
  ScheduledDateTimeData,
  'id',
  'created_at',
  'updated_at',
  'activityLogs',
  'scheduledDateTimeUsers',
  'users'
>;

/**
 * Update ScheduledDateTime data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateScheduledDateTimeData = Partial<
  Omit<
    ScheduledDateTimeData,
    'id',
    'created_at',
    'updated_at',
    'activityLogs',
    'scheduledDateTimeUsers',
    'users'
  >
>;
