/**
 * ScheduledDateTimeUserData - TypeScript interface for scheduled_date_time_users table
 *
 * ⚠️  Do not edit this file manually - it will be regenerated
 * To customize: Modify Rails model or run: rails generate zero:active_models
 */

import type { BaseRecord } from '../base/types';

/**
 * Complete ScheduledDateTimeUser record interface
 * Matches the database schema exactly with optional relationships
 */
export interface ScheduledDateTimeUserData extends BaseRecord {
  id: string;
  created_at: string | number;
  updated_at: string | number;
  scheduled_date_time_id?: string;
  user_id?: string;
}

/**
 * Create ScheduledDateTimeUser data interface
 * Excludes auto-generated fields and relationships
 */
export type CreateScheduledDateTimeUserData = Omit<
  ScheduledDateTimeUserData,
  'id',
  'created_at',
  'updated_at'
>;

/**
 * Update ScheduledDateTimeUser data interface
 * All fields optional except id, excludes relationships
 */
export type UpdateScheduledDateTimeUserData = Partial<
  Omit<ScheduledDateTimeUserData, 'id', 'created_at', 'updated_at'>
>;
